<a href="https://colab.research.google.com/github/KanishThakkar/PyTorch-Basics-and-Neural-Network/blob/main/Pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np
print(torch.__version__)

2.9.0+cpu


We can create Scaler, Vector,Matrix and Tensor using torch.tensor()

In [ ]:
#create scaler
scaler = torch.tensor(1)
scaler

tensor(1)

In [ ]:
#dimention of scaler
print(scaler.ndim)

0


In [ ]:
#Get tensor back as python int
scaler.item()

1

In [ ]:
#create vector
vector = torch.tensor([1,2])
vector

tensor([1, 2])

In [ ]:
#dimention and shape of vector
print(vector.ndim)
print(vector.shape)

1
torch.Size([2])


In [ ]:
#create matrix
MATRIX = torch.tensor([[1,2],
                      [3,4]])
MATRIX

tensor([[1, 2],
        [3, 4]])

In [ ]:
#dim of matrix
MATRIX.ndim

2

In [ ]:
#shape of matrix
MATRIX.shape

torch.Size([2, 2])

In [ ]:
#create tensor
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
#dim of TENSOR
TENSOR.ndim

3

In [ ]:
#shape of tensor
TENSOR.shape

torch.Size([1, 3, 3])

Here above shape(1,3,3) tells that it has 1 dimention of  3x3

###Random Tensors
####Why we use random Tensors?
Random Tensors are imp because the way Neural network start learning is that by using many Random tensors and adjust those number to better represent of their data

In code - torch.rand(shape)

In [ ]:
#create random tensors
Random_tensors = torch.rand(3,4)
Random_tensors

tensor([[0.2809, 0.2489, 0.8432, 0.0124],
        [0.8937, 0.7445, 0.3706, 0.2230],
        [0.2413, 0.8075, 0.4821, 0.0881]])

In [ ]:
#create random tensor simillar to an image shape tensor
Image_Tensor = torch.rand(size = (224,224,3))   # here 224x224 is widhth x hight and 3 are color channel (R,G,B)
Image_Tensor

tensor([[[0.8117, 0.8497, 0.2942],
         [0.1043, 0.4309, 0.5938],
         [0.0191, 0.6827, 0.5882],
         ...,
         [0.5356, 0.9083, 0.2901],
         [0.1095, 0.6253, 0.7317],
         [0.6688, 0.8065, 0.3266]],

        [[0.7696, 0.1544, 0.0194],
         [0.0526, 0.1488, 0.3959],
         [0.9692, 0.3871, 0.3004],
         ...,
         [0.1795, 0.2225, 0.0441],
         [0.1301, 0.8746, 0.2575],
         [0.4500, 0.6158, 0.7439]],

        [[0.6882, 0.8992, 0.8494],
         [0.1144, 0.1181, 0.4884],
         [0.5546, 0.2526, 0.9142],
         ...,
         [0.0409, 0.9597, 0.7837],
         [0.6711, 0.2305, 0.4763],
         [0.9397, 0.7366, 0.0477]],

        ...,

        [[0.3584, 0.4319, 0.0846],
         [0.5099, 0.5114, 0.6076],
         [0.0519, 0.4870, 0.0091],
         ...,
         [0.1796, 0.9534, 0.6993],
         [0.8065, 0.8859, 0.9957],
         [0.0236, 0.9824, 0.8557]],

        [[0.1708, 0.1728, 0.3333],
         [0.3645, 0.8087, 0.6200],
         [0.

Create a tensor with all ones and zeros

In [ ]:
# tensor with all zeros
Zeros = torch.zeros(3,4)
Zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# tensor with all ones
Ones = torch.ones(3,4)
Ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

Creating Range of Tensors

In [ ]:
Range_tensors = torch.arange(start =0,end = 11,step = 2)
Range_tensors

tensor([ 0,  2,  4,  6,  8, 10])

In [ ]:
# creating Tensors like
# if you want to create a tensor of zeros with  same size as Range_tensors
Zeros_same_shape_tensors = torch.zeros_like(input =Range_tensors)
Zeros_same_shape_tensors

tensor([0, 0, 0, 0, 0, 0])

Tensor Data type

In [ ]:
float_32_tensors = torch.tensor([1.0,2.0,3.0,4.0],dtype = None, # dtype = datatype of your tensor
                                device = None, # What device is your Tensor on
                                requires_grad=False) # Whether or not to tracl gradiant with the tensor operation
float_32_tensors

tensor([1., 2., 3., 4.])

In [ ]:
float_32_tensors.dtype

torch.float32

In [ ]:
# if you need to convert this tensor on float16 tensor
float_16_tensors = float_32_tensors.type(torch.float16)
float_16_tensors.dtype

torch.float16

###Matrix Multiplication
1. Element wise multiplication
2. Matrix multiplication (Dot product)

###Matrix Multiplication Rules:
* Inner Dimention must match
e.x (2,3) @ (2,3) -> won't work
    (2,3) @ (3,2) -> work
* The resulten shape of matrix multiplication is its outer shape
e.x (2,3) @ (2,3) -> Output matrix shape = (2,2)

In [ ]:
#Element wise multiplication
print(TENSOR ,"*", TENSOR)
print("        ")
print(TENSOR * TENSOR)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]) * tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
        
tensor([[[ 1,  4,  9],
         [16, 25, 36],
         [49, 64, 81]]])


In [ ]:
#Matrix multiplication
torch.matmul(TENSOR,TENSOR)

tensor([[[ 30,  36,  42],
         [ 66,  81,  96],
         [102, 126, 150]]])

To fix the tensor shape issue we can manipulate one of the tensor to be transpose.  

In [ ]:
tensor_a = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_b  = torch.tensor([[7,10],
                          [8,11],
                          [9,12]])

* torch.matmul(tensor_a,tensor_b) # give us error because it cant satisfied matrix mul. rules

In [ ]:
#TO fix this we use to transpose one of the matrix
print(tensor_b.T) # it will transpose the matrix from (3,2) -> (2,3)
print("")
print(tensor_b.T.shape)
print(" ")
print(torch.matmul(tensor_a,tensor_b.T))

tensor([[ 7,  8,  9],
        [10, 11, 12]])

torch.Size([2, 3])
 
tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


###Tensor Aggrigation
Find min,max,mean ,sum etc.

In [ ]:
ex = torch.arange(0,11,2) # example tensor
ex

tensor([ 0,  2,  4,  6,  8, 10])

In [ ]:
print(torch.min(ex)) # minimum element
print(torch.max(ex)) #maximum element
print(torch.mean(ex.type(torch.float32))) # always use .type whild doing mean of tensor because 'mean' only support in float32 and long value and complex values
print(torch.sum(ex)) # sum of elements

tensor(0)
tensor(10)
tensor(5.)
tensor(30)


###Arg__()
Argmax - help to find index of maximum value from the given list or tensor
Argmin - helo to find tndex of minimum value from the given list or tensor

In [1]:
ex

NameError: name 'ex' is not defined

In [2]:
print(torch.argmin(ex))
print(torch.argmax(ex)) #means a =t poistion 5th it has maximum value. here it is 10

NameError: name 'torch' is not defined

### Reshaping , stacking , squezzing and unsquezzing Tensors
* Reshape - Reshape input tensor to defined shape
* View - Return the view of the input tensor but share same memory as input tensor
* stacking - combining multimple tensor on top of each other
* squezzing -remove all 1 dimention of tensor
* unsquezzing - add a 1 dimention of tensor
* permute - Return a view of tensor with dimention swapped in a certain way


In [ ]:
ex,ex.shape

(tensor([ 0,  2,  4,  6,  8, 10]), torch.Size([6]))

In [ ]:
ex.reshape(1,6) # add an extra dimention..!

tensor([[ 0,  2,  4,  6,  8, 10]])

In [ ]:
z = ex.view(1,6) # here z is view of x
z, z.shape

(tensor([[ 0,  2,  4,  6,  8, 10]]), torch.Size([1, 6]))

In [ ]:
z[:,0] = 5  # here changes in z effect on x because z and x share same memory
z,ex

(tensor([[ 5,  2,  4,  6,  8, 10]]), tensor([ 5,  2,  4,  6,  8, 10]))

In [ ]:
# stack  - on top of each other
ex_stacked = torch.stack((ex,ex,ex,ex),dim = 0) # dim 0 means row wise stack
ex_stacked

tensor([[ 5,  2,  4,  6,  8, 10],
        [ 5,  2,  4,  6,  8, 10],
        [ 5,  2,  4,  6,  8, 10],
        [ 5,  2,  4,  6,  8, 10]])

In [ ]:
ex_stacked = torch.stack((ex,ex,ex,ex),dim = 1) # dim 1 means column wise stack
ex_stacked

tensor([[ 5,  5,  5,  5],
        [ 2,  2,  2,  2],
        [ 4,  4,  4,  4],
        [ 6,  6,  6,  6],
        [ 8,  8,  8,  8],
        [10, 10, 10, 10]])

In [ ]:
# squeeze method
print(f"privious arrray size :{ex.reshape(1,6).shape}")   # remove all 1 dimetnion from the original tensor shape
ex_squeezed = torch.squeeze(ex.reshape(1,6))
print("after squeezing")
print(f"New dimention are:{ex_squeezed.shape}")

#Unsqueeze method
print("after unsqueezing")
ex_unsqueezed = torch.unsqueeze(ex_squeezed,dim = 0)  # add 1 dimention by row or colum wise
print(f"unsqueeze dimention are{ex_unsqueezed.shape}")

# permute
x = torch.randn(3,4,6)
print(x.shape)
print(f"After permute :{x.permute(2,1,0).shape}")  #you can change tensor dimention by your self using permute

privious arrray size :torch.Size([1, 6])
after squeezing
New dimention are:torch.Size([6])
after unsqueezing
unsqueeze dimention aretorch.Size([1, 6])
torch.Size([3, 4, 6])
After permute :torch.Size([6, 4, 3])


### Converting numpy array into pytorch tensor and converting back pytorch Tensor to numpy array
* Numpy array -> pytorch tensor   = torch.from_numpy(array)
* pytorch tensor -> numpy array = torch.numpy(array)


In [ ]:
import numpy as np
array = np.arange(1.0,6.0)
array_from_numpy = torch.from_numpy(array)
print(f"numpy array:{array}")
print(f"pytorch tensor:{array_from_numpy}")
print("")
print(f"dtype of numpy array:{array.dtype}")
print(f"dtype of pytorch tensor:{array_from_numpy.dtype}")


numpy array:[1. 2. 3. 4. 5.]
pytorch tensor:tensor([1., 2., 3., 4., 5.], dtype=torch.float64)

dtype of numpy array:float64
dtype of pytorch tensor:torch.float64


### Reproducibility (trying to take the random out of random)
How does this relate to neural networks and deep learning?

start with random numbers -> tensor operations -> try to make better (again and again and again)

For example, you create an algorithm capable of achieving X performance.
And then your friend tries it out to verify you're not crazy.
How could they do such a thing?
That's where reproducibility comes in.

* To reduce randomness in pytorch there is concept of `random seed`
Essentially what the random seed does is flavour the randomness

In [ ]:
A = torch.rand(2,3)
B = torch.rand(2,3)
print(A)
print(B)
print(A == B)   # so basically all time when you run it, it will give you diff diff output so reduce the randomness we use Random seef

tensor([[0.1185, 0.8885, 0.4388],
        [0.8705, 0.4835, 0.4209]])
tensor([[0.9542, 0.5583, 0.7481],
        [0.1548, 0.2610, 0.2150]])
tensor([[False, False, False],
        [False, False, False]])


In [ ]:
RANDOM_SEED = 42 #42 is ideal number for seeds , you can use whatever you want
torch.manual_seed(RANDOM_SEED)
C = torch.rand(2,3)
torch.manual_seed(RANDOM_SEED)
D = torch.rand(2,3)
print(C)
print(D)
print(C==D)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])
tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])
tensor([[True, True, True],
        [True, True, True]])


### Putting tensor on gpu


In [ ]:
# first set device name to cuda .cuda is gpu name for nvidia
device = "cuda"
tensor = torch.tensor([1,2,3])
# check if gpu is available
device = "cuda" if torch.cuda.is_available() else "cpu"
device

# count number of device on gpu
torch.cuda.device_count()

#Transfer this tensor from cpu to gpu
tensor_on_gpu = tensor.to(device)
tensor_on_gpu # we can convert tensor in numpy array when is in gpu.. to do this we need to convert back into cpu and then use it

# convert that tensor from gpu to cpu
tensor_on_cpu = tensor_on_gpu.cpu()
tensor_on_cpu.numpy()

array([1, 2, 3])

In [ ]:
print("hello")

hello
